version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - api-network

networks:
  api-network:
    driver: bridge